name: Deploy Next.js static site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout repo
      - uses: actions/checkout@v3

      # 2) set Node
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3) install & build  (note the working-directory)
      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Build static site
        run: npm run build          # ← creates  web/out/
        working-directory: web

      # 4) publish /web/out to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/out
